### ISSUE TITLE
wip: trailer widget

### ISSUE THREAD

**Issue by erikabusiness** [erikabusiness/dart_plus_app#44]
# Problema no widget de trailer
Criei um widget contendo um player que reproduz vídeos diretamente do youtube de acordo com a [documentacão da lib](https://pub.dev/packages/youtube_player_flutter) mas não obtive êxito ao renderizar o vídeo na tela. Alguém consegue me ajudar a identificar o problema?

obs: procurei em vídeos do youtube e a lógica está batendo com a minha.

![image](https://github.com/erikabusiness/dart_plus_app/assets/62026942/2c82bee0-3bb3-4b42-b58b-671d6d77ea27)

**Comment by jaquedreyer** [comment]
Issue resolvida em _pair programming_ (Erika, Jaque e Fran) 💜

**Comment by jaquedreyer** [comment]
Issue resolvida em pair programming (Erika, Jaque e Fran) 💜
