### ISSUE TITLE
Bug na versão do SDK

### ISSUE THREAD

**Issue by erikabusiness** [erikabusiness/dart_plus_app#51]
# Caso apresente esse erro ao executar a aplicacão:

![Captura de tela 2024-05-18 225052](https://github.com/erikabusiness/dart_plus_app/assets/62026942/f1db1c55-fdb8-41c0-b8fa-339e0834bcd6)

# Troque `minSdkVersion flutter.minSdkVersion` por  `minSdkVersion 21` dentro de `android\app\build.gradle` assim:

![image](https://github.com/erikabusiness/dart_plus_app/assets/62026942/69e7698d-af03-443b-8008-58380d31c6fc)

**Comment by jaquedreyer** [comment]
Valeu pela dica, foi bastante útil! 😍
